# Just based ubuntu and XRT of pci is no use for zcu102
FROM ubuntu:16.04
#COPY sources.list /etc/apt/
#RUN apt-get update && apt-get install -y --allow-unauthenticated pciutils net-tools lsb-release iputils-ping openssh-client openssh-server vim ocl-icd-opencl-dev libboost-dev libboost-filesystem-dev uuid-dev dkms libprotoc-dev protobuf-compiler
#COPY xrt_201830.2.1.0_16.04-xrt.deb /opt/
#RUN apt install -y -f --allow-unauthenticated /opt/xrt_201830.2.1.0_16.04-xrt.deb
